# Understanding Stages > Stage > Jobs > Job > Steps > Script
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ArtifactGenerate
    jobs:
        - job: 
          steps:
          - script: mvn install -DskipTests
            displayName: Maven Install
          
          - script: mvn test
            displayName: Maven Test

  - stage: DockerBuild_and_Push
    jobs:
        - job: 
          steps:
          - script: docker build -t azkabegh/ado:azure-$(Build.BuildNumber) ./
            displayName: Docker Build

          - script: docker images | grep azkabegh
            displayName: Print the existing Docker Images

          - script: docker login -u $(dockerUserName) --password-stdin <<<$(dockerPassword)
            displayName: Docker Login

          - script: docker push azkabegh/ado:azure-$(Build.BuildNumber)
            displayName: Docker Push
          
