# In your project, go to the settings > Service Settings > Add credentials for DockerHub.
# Then create a pipeline with Docker Task and select the Dockerhub service and repository and tag where the image will be pushed
# There is a command for build and push in one task
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Docker
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'azkabegh/ado'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(Build.BuildNumber)'
        
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'azkabegh/ado'
        command: 'push'
        tags: '$(Build.BuildNumber)'
