# This will run the same inline script on two diffrent agents
trigger:
- master

strategy:
  matrix:
     linux:
       operatingSystem: 'ubuntu-latest'
     mac:
       operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Hello
  displayName: hello print
