# While editing the yaml, there is a variables option right before Save.
# Here we can give the variable a name and a value. Then this variable can be called in the script. If Bash is used, $(variable). For powershell, (env:variable).
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
# Two steps and last one has a name
    - bash: echo This is a build job.
    - bash: echo $(PipelineLevelVariable)
      displayName: 'Run a one-line script'
- stage: Test
  jobs:
  - job: Job2
    steps:
    - script: echo testing
      displayName: 'Run a multi-line script'
